/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hmt.hocmay.main;

import hmt.hocmay.utility.Ultilities;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Tuan
 */
public class MainFrame extends javax.swing.JFrame {

    private int spam;
    private int nonSpam;
    private HashMap<String, String> trainning;
    private JFileChooser fc;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        trainning = new HashMap();
        fc = new JFileChooser();
        spam = 0;
        nonSpam = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filePath = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        typeAction = new javax.swing.JComboBox<>();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        contentTest = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentTrainning = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filePath.setEditable(false);
        filePath.setToolTipText("URL");
        filePath.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setText("Select File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        typeAction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trainning", "Thư rác", "Thư thường" }));
        typeAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionActionPerformed(evt);
            }
        });

        contentTest.setColumns(20);
        contentTest.setRows(5);
        jScrollPane2.setViewportView(contentTest);

        jLabel1.setText("Nội dung");

        jButton4.setText("Show");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Check");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane3.addTab("tab1", jPanel1);

        contentTrainning.setColumns(20);
        contentTrainning.setRows(5);
        jScrollPane1.setViewportView(contentTrainning);

        jLabel2.setText("Nội dung");

        jButton2.setText("Action");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ghi file");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(0, 83, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane3.addTab("tab2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filePath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(typeAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane3)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Chọn file
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            filePath.setText(file.getAbsolutePath());
        } else {
            // Something smart there!
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void typeActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (typeAction.getSelectedIndex() == 0) { // Nếu là file trainning
            try {
                BufferedReader in = new BufferedReader(new FileReader(filePath.getText()));
                spam = 0;
                nonSpam = 0;
                trainning.clear();
                String[] str = in.readLine().split(" ");
                spam = Integer.parseInt(str[0]);
                nonSpam = Integer.parseInt(str[1]);
                contentTrainning.setText("Có " + spam + " bộ dữ liệu mẫu là thư rác\nCó " + nonSpam + " bộ dữ liệu mẫu là thư thường\n");
                String inputLine = in.readLine();
                while (inputLine != null) {
                    str = inputLine.split(" ");
                    trainning.put(str[0], str[1] + " " + str[2]);
                    String s = str[0] + ":\n"
                            + "  Xuất hiện " + str[1] + " lần trong thư thường\n"
                            + "  Xuất hiện " + str[2] + " lần trong thư rác\n";
                    contentTrainning.setText(contentTrainning.getText() + s);
                    inputLine = in.readLine();
                }

                in.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            ArrayList<String> str = Ultilities.getWords(filePath.getText());
            contentTrainning.setText("");
            if (typeAction.getSelectedIndex() == 1) { //Nếu là thư rác
                spam++;
                for (int i = 0; i < str.size(); i++) {
                    if (trainning.containsKey(str.get(i))) {
                        String[] count = trainning.get(str.get(i)).split(" ");
                        int newValue = Integer.parseInt(count[1]) + 1;
                        trainning.put(str.get(i), count[0] + " " + newValue);
                        String s = str.get(i) + ":\n"
                                + "  Xuất hiện " + count[0] + " lần trong thư thường\n"
                                + "  Xuất hiện " + newValue + " lần trong thư rác\n";
                        contentTrainning.setText(contentTrainning.getText() + "\n" + s);
                    } else {
                        trainning.put(str.get(i), "0 1");
                        String s = str.get(i) + ":\n"
                                + "  Xuất hiện 0 lần trong thư thường\n"
                                + "  Xuất hiện 1 lần trong thư rác\n";
                        contentTrainning.setText(contentTrainning.getText() + "\n" + s);
                    }
                }
            } else { // Nếu là thư thường
                nonSpam++;
                for (int i = 0; i < str.size(); i++) {
                    if (trainning.containsKey(str.get(i))) {
                        String[] count = trainning.get(str.get(i)).split(" ");
                        int newValue = Integer.parseInt(count[0]) + 1;
                        trainning.put(str.get(i), newValue + " " + count[1]);
                        String s = str.get(i) + ":\n"
                                + "  Xuất hiện " + newValue + " lần trong thư thường\n"
                                + "  Xuất hiện " + count[1] + " lần trong thư rác\n";
                        contentTrainning.setText(contentTrainning.getText() + "\n" + s);
                    } else {
                        trainning.put(str.get(i), "1 0");
                        String s = str.get(i) + ":\n"
                                + "  Xuất hiện 1 lần trong thư thường\n"
                                + "  Xuất hiện 0 lần trong thư rác\n";
                        contentTrainning.setText(contentTrainning.getText() + "\n" + s);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        fc.setDialogTitle("Specify a file to save");
        int userSelection = fc.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            try {
                PrintWriter writer;
                File fileToSave = fc.getSelectedFile();
                writer = new PrintWriter(new FileWriter(fileToSave.getAbsolutePath()));
                writer.println(spam + " " + nonSpam);
                for (String key : trainning.keySet()) {
                    writer.println(key + " " + trainning.get(key));
                }
                writer.close();
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            //Something smart there!
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            BufferedReader in = new BufferedReader(new FileReader(filePath.getText()));
            contentTest.setText("");
            String inputLine = in.readLine();
            while (inputLine != null) {
                contentTest.setText(contentTest.getText() + inputLine + "\n");
                inputLine = in.readLine();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ArrayList<String> str = Ultilities.getWords(filePath.getText());
        contentTest.setText("");
        //Tính xác suất đối với thư thường
        double pNonSpam = 0;
        for(int i=0;i<str.size();i++){
            if(trainning.containsKey(str.get(i))){
                double temp = Double.parseDouble(trainning.get(str.get(i)).split(" ")[0])/nonSpam;
                if(temp != 0){
                    pNonSpam += Math.log(temp);
                }
            }
        }
        pNonSpam+=Math.log((double)nonSpam/(nonSpam+spam));
        //Tính xác suất đối với thư rác
        double pSpam = 0;
        for(int i=0;i<str.size();i++){
            if(trainning.containsKey(str.get(i))){
                double temp = Double.parseDouble(trainning.get(str.get(i)).split(" ")[1])/spam;
                if(temp != 0){
                    pSpam += Math.log(temp);
                }
            }
        }
        pSpam+=Math.log((double)spam/(nonSpam+spam));
        System.out.println(pNonSpam+" "+pSpam);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea contentTest;
    private javax.swing.JTextArea contentTrainning;
    private javax.swing.JTextField filePath;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JComboBox<String> typeAction;
    // End of variables declaration//GEN-END:variables
}
